import './main.scss';
import './assets/logo.png';
import './assets/profile-1.jpg';
import './assets/profile-2.jpg';
import './assets/profile-3.jpg';
import './assets/profile-4.jpg';
import './assets/profile-5.jpg';
import './assets/profile-6.jpg';
import './assets/hero.png';
import './assets/hero.webp';
import './assets/hero-min.png';
import './assets/featured-1.png';
import './assets/featured-2.png';
import './assets/featured-3.png';
import './assets/featured-4.png';
import './assets/featured-5.png';
import './assets/app-1.png';
import './assets/app-2.png';
import './assets/app-3.png';
import './assets/meal-1.jpg';
import './assets/meal-2.jpg';
import './assets/testimonial-1.jpg';
import './assets/testimonial-2.jpg';
import './assets/testimonial-3.jpg';
import './assets/testimonial-4.jpg';
import './assets/testimonials-gallery-1.jpg';
import './assets/testimonials-gallery-2.jpg';
import './assets/testimonials-gallery-3.jpg';
import './assets/testimonials-gallery-4.jpg';
import './assets/testimonials-gallery-5.jpg';
import './assets/testimonials-gallery-6.jpg';
import './assets/testimonials-gallery-7.jpg';
import './assets/testimonials-gallery-8.jpg';
import './assets/testimonials-gallery-9.jpg';
import './assets/testimonials-gallery-10.jpg';
import './assets/testimonials-gallery-11.jpg';
import './assets/testimonials-gallery-12.jpg';
import './assets/eating.jpg';

import navBar from './modules/navbar.js';
import linksHelper from './modules/linksHelper.js';
import stickyNav from './modules/stickyNav.js';

navBar();
linksHelper();
stickyNav();
